os: linux
dist: focal

language: python

python:
  - "3.8"

before_install:
  - openssl aes-256-cbc -K $encrypted_37e077de7c13_key -iv $encrypted_37e077de7c13_iv -in lab-devops-cloud-arthur-9060070a55c3.json.enc -out ../lab-devops-cloud-arthur-9060070a55c3.json -d

install:
  - pip install flask

script:
  - python -m unittest -v test

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  edge: true
  app: labdevops-arthur
  on:
    branch: main  

deploy:
    provider: gae
    keyfile: ../lab-devops-cloud-arthur-9060070a55c3.json
    project: lab-devops-cloud-arthur
    on:
      branch: main